### ISSUE TITLE
Version 0.13 has packaging problem

### ISSUE THREAD

**Issue by gbenson-wikia** [sergedomk/fiql_parser#1]
0.12 installs just fine via pip, but version 0.13 doesn't actually install a working egg - probably just a dumb packaging config typo.  ;)

Steps to reproduce:
1) in a clean virtualenv: $ pip install fiql-parser
2) python
3) >>> import fql_parser

Expected result:
Module should be imported

Actual result:
Unknown module error

**Comment by sergedomk** [comment]
Updated packaging code and uploaded 0.14 to pypi.
